import { Ticket, ProgressUpdate, TicketStatus, TTRCompliance } from '@/types/ticket';
import { TicketWithProgress, ProgressUpdateRow } from '@/hooks/useTickets';

export const mapDbTicketToTicket = (dbTicket: TicketWithProgress): Ticket => ({
  id: dbTicket.id,
  provider: dbTicket.provider || 'TSEL',
  incNumbers: dbTicket.inc_numbers,
  siteCode: dbTicket.site_code,
  siteName: dbTicket.site_name,
  networkElement: dbTicket.network_element || undefined,
  kategori: dbTicket.kategori || '',
  lokasiText: dbTicket.lokasi_text || '',
  latitude: dbTicket.latitude || undefined,
  longitude: dbTicket.longitude || undefined,
  jarakKmRange: dbTicket.jarak_km?.toString() || undefined,
  ttrCompliance: (dbTicket.ttr_compliance || 'COMPLY') as TTRCompliance,
  jamOpen: new Date(dbTicket.jam_open),
  ttrTargetHours: dbTicket.ttr_target_hours,
  maxJamClose: new Date(dbTicket.max_jam_close),
  ttrRealHours: undefined,
  sisaTtrHours: dbTicket.sisa_ttr_hours || 0,
  status: (dbTicket.status || 'OPEN') as TicketStatus,
  isPermanent: false,
  permanentNotes: undefined,
  penyebab: dbTicket.penyebab || undefined,
  segmen: dbTicket.segment || undefined,
  incGamas: undefined,
  kjd: undefined,
  teknisiList: dbTicket.teknisi_list || undefined,
  assignedTo: dbTicket.assigned_to || undefined,
  assignedAt: undefined,
  assignedBy: undefined,
  createdByAdmin: dbTicket.created_by || '',
  createdAt: new Date(dbTicket.created_at),
  updatedAt: new Date(dbTicket.updated_at),
  rawTicketText: undefined,
  progressUpdates: dbTicket.progress_updates?.map(mapDbProgressToProgress) || [],
  adminNotes: undefined,
});

export const mapDbProgressToProgress = (pu: ProgressUpdateRow): ProgressUpdate => ({
  id: pu.id,
  ticketId: pu.ticket_id,
  timestamp: new Date(pu.timestamp),
  source: pu.source as 'HD' | 'ADMIN' | 'SYSTEM',
  message: pu.message,
  statusAfterUpdate: (pu.status_after_update || undefined) as TicketStatus | undefined,
  locationUpdate: undefined,
  attachments: undefined,
  createdBy: pu.created_by || '',
});

export const mapTicketToDbInsert = (ticket: Partial<Ticket>, userId?: string) => ({
  provider: ticket.provider || 'TSEL',
  inc_numbers: ticket.incNumbers || [],
  site_code: ticket.siteCode || '',
  site_name: ticket.siteName || '',
  network_element: ticket.networkElement,
  kategori: ticket.kategori || '',
  lokasi_text: ticket.lokasiText || '',
  latitude: ticket.latitude,
  longitude: ticket.longitude,
  jarak_km: ticket.jarakKmRange ? parseFloat(ticket.jarakKmRange) : null,
  ttr_compliance: ticket.ttrCompliance || 'COMPLY',
  jam_open: ticket.jamOpen?.toISOString() || new Date().toISOString(),
  ttr_target_hours: ticket.ttrTargetHours || 24,
  max_jam_close: ticket.maxJamClose?.toISOString() || new Date().toISOString(),
  sisa_ttr_hours: ticket.sisaTtrHours || 0,
  status: ticket.status || 'OPEN',
  penyebab: ticket.penyebab,
  segment: ticket.segmen,
  teknisi_list: ticket.teknisiList,
  assigned_to: ticket.assignedTo,
  created_by: userId,
});
