import { Ticket, ProgressUpdate } from '@/types/ticket';
import { TicketWithProgress, ProgressUpdateRow } from '@/hooks/useTickets';

export const mapDbTicketToTicket = (dbTicket: TicketWithProgress): Ticket => ({
  id: dbTicket.id,
  provider: dbTicket.provider,
  incNumbers: dbTicket.inc_numbers,
  siteCode: dbTicket.site_code,
  siteName: dbTicket.site_name,
  networkElement: dbTicket.network_element || undefined,
  kategori: dbTicket.kategori,
  lokasiText: dbTicket.lokasi_text,
  latitude: dbTicket.latitude || undefined,
  longitude: dbTicket.longitude || undefined,
  jarakKmRange: dbTicket.jarak_km_range || undefined,
  ttrCompliance: dbTicket.ttr_compliance,
  jamOpen: new Date(dbTicket.jam_open),
  ttrTargetHours: dbTicket.ttr_target_hours,
  maxJamClose: new Date(dbTicket.max_jam_close),
  ttrRealHours: dbTicket.ttr_real_hours || undefined,
  sisaTtrHours: dbTicket.sisa_ttr_hours,
  status: dbTicket.status,
  isPermanent: dbTicket.is_permanent,
  permanentNotes: dbTicket.permanent_notes || undefined,
  penyebab: dbTicket.penyebab || undefined,
  segmen: dbTicket.segmen || undefined,
  incGamas: dbTicket.inc_gamas || undefined,
  kjd: dbTicket.kjd || undefined,
  teknisiList: dbTicket.teknisi_list || undefined,
  assignedTo: dbTicket.assigned_to || undefined,
  assignedAt: dbTicket.assigned_at ? new Date(dbTicket.assigned_at) : undefined,
  assignedBy: dbTicket.assigned_by || undefined,
  createdByAdmin: dbTicket.created_by || '',
  createdAt: new Date(dbTicket.created_at),
  updatedAt: new Date(dbTicket.updated_at),
  rawTicketText: dbTicket.raw_ticket_text || undefined,
  progressUpdates: dbTicket.progress_updates?.map(mapDbProgressToProgress) || [],
  adminNotes: dbTicket.admin_notes || undefined,
});

export const mapDbProgressToProgress = (pu: ProgressUpdateRow): ProgressUpdate => ({
  id: pu.id,
  ticketId: pu.ticket_id,
  timestamp: new Date(pu.timestamp),
  source: pu.source as 'HD' | 'ADMIN' | 'SYSTEM',
  message: pu.message,
  statusAfterUpdate: pu.status_after_update || undefined,
  locationUpdate: pu.location_lat && pu.location_lon 
    ? { lat: pu.location_lat, lon: pu.location_lon } 
    : undefined,
  attachments: pu.attachments || undefined,
  createdBy: pu.created_by || '',
});

export const mapTicketToDbInsert = (ticket: Partial<Ticket>, userId?: string) => ({
  provider: ticket.provider || 'TSEL',
  inc_numbers: ticket.incNumbers || [],
  site_code: ticket.siteCode || '',
  site_name: ticket.siteName || '',
  network_element: ticket.networkElement,
  kategori: ticket.kategori || '',
  lokasi_text: ticket.lokasiText || '',
  latitude: ticket.latitude,
  longitude: ticket.longitude,
  jarak_km_range: ticket.jarakKmRange,
  ttr_compliance: ticket.ttrCompliance || 'COMPLY',
  jam_open: ticket.jamOpen?.toISOString() || new Date().toISOString(),
  ttr_target_hours: ticket.ttrTargetHours || 24,
  max_jam_close: ticket.maxJamClose?.toISOString() || new Date().toISOString(),
  ttr_real_hours: ticket.ttrRealHours,
  sisa_ttr_hours: ticket.sisaTtrHours || 0,
  status: ticket.status || 'OPEN',
  is_permanent: ticket.isPermanent || false,
  permanent_notes: ticket.permanentNotes,
  penyebab: ticket.penyebab,
  segmen: ticket.segmen,
  inc_gamas: ticket.incGamas,
  kjd: ticket.kjd,
  teknisi_list: ticket.teknisiList,
  assigned_to: ticket.assignedTo,
  assigned_at: ticket.assignedAt?.toISOString(),
  assigned_by: ticket.assignedBy,
  created_by: userId,
  raw_ticket_text: ticket.rawTicketText,
  admin_notes: ticket.adminNotes,
});
